apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: aci-adr-payment
  namespace: default
  labels:
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: aci-adr-payment
spec:
  source:
    git:
      url: https://github.com/aci-adr/aci-adr-payment
      ref:
        branch: main